#!/data/data/com.termux/files/usr/bin/bash
# Project name : Fam-Hacker_Client
# Coded by: tthatgguy1 (You dont become a coder by just changing the credits)
# Github: https://github.com/tthatgguy1/Fam-Hacker_Client
# Date : 12/04/2024

## Sound 1
clear
mpv ~/storage/shared/Fam-Hacker_Client/sfx/Secret_Sound.mp3 >/dev/null 2>/dev/null
echo " "
echo " "
sleep 1.0

## Torrent Logo & Date
echo " "
echo " "
clear
echo '
─███████╗╔█████╗─███╗───███╗─██╗──██╗╔█████╗─╔██████╗██╗──██╗██████╗─
─██╔════╝██╔══██╗████╗─████║─██║──██║██╔══██╗██╔════╝██║─██╔╝██╔══██╗
─█████╗──███████║██╔████╔██║─███████║███████║██║─────█████╔╝─██████╔╝
─██╔══╝──██╔══██║██║╚██╔╝██║─██╔══██║██╔══██║██║─────██╔═██╗─██╔══██╗
─██║─────██║──██║██║─╚═╝─██║─██║──██║██║──██║╚██████╗██║──██╗██║──██║
─╚═╝─────╚═╝──╚═╝╚═╝─────╚═╝─╚═╝──╚═╝╚═╝──╚═╝─╚═════╝╚═╝──╚═╝╚═╝──╚═╝
───████████╗╔██████╗─██████╗─██████╗─███████╗███╗───██╗████████╗─────
───╚══██╔══╝██╔═══██╗██╔══██╗██╔══██╗██╔════╝████╗──██║╚══██╔══╝─────
──────██║───██║───██║██████╔╝██████╔╝█████╗──██╔██╗─██║───██║────────
──────██║───██║───██║██╔══██╗██╔══██╗██╔══╝──██║╚██╗██║───██║────────
──────██║───╚██████╔╝██║──██║██║──██║███████╗██║─╚████║───██║────────
──────╚═╝────╚═════╝─╚═╝──╚═╝╚═╝──╚═╝╚══════╝╚═╝──╚═══╝───╚═╝────────
──────────╔██████╗██╗─────██╗███████╗███╗───██╗████████╗─────────────
──────────██╔════╝██║─────██║██╔════╝████╗──██║╚══██╔══╝─────────────
──────────██║─────██║─────██║█████╗──██╔██╗─██║───██║────────────────
──────────██║─────██║─────██║██╔══╝──██║╚██╗██║───██║────────────────
──────────╚██████╗███████╗██║███████╗██║─╚████║───██║────────────────
───────────╚═════╝╚══════╝╚═╝╚══════╝╚═╝──╚═══╝───╚═╝────────────────

---------------------------[Nah-Fam_Studios]------------------------------' | lolcat
echo " "
date +"%l:%M:%S %p" | lolcat --animate -d 15

## File Info
cd downloads
newf=$(ls -Art | tail -n 1)
echo " "
cowsay -r "${newf}" | lolcat
toilet -f smascii12 -f smascii9 'Starting' -F border | lolcat \-a
echo " "
sleep 1.0

## Aria2 Download
echo -e  "To \033[1;31mQuit\033[0m press \033[1;31mctrl\033[0m \033[1;33m+\033[0m \033[1;31mC\033[0m \033[1;33mtogether\033[0m, and then press \033[1;33mEnter\033[0m"
echo " "
"aria2c" --select-file=1 --seed-time=0 --summary-interval=5000 --max-connection-per-server=16 -d /data/data/com.termux/files/home/storage/shared/Fam-Hacker_Client "/data/data/com.termux/files/home/downloads/${newf}"
echo " "
echo " "

## Sound 2
mpv ~/storage/shared/Fam-Hacker_Client/sfx/MMF.mp3 >/dev/null 2>/dev/null
mpv ~/storage/shared/Fam-Hacker_Client/sfx/TLOZ-WW_Heart_Container.mp3 >/dev/null 2>/dev/null
echo " "
echo " "
sleep 1.0

## Termux Move
echo " "
echo " "
echo " "
echo " "
echo -e "\e[34mDirecting\e[0m \e[33mTermux\e[0m \e[34mto\e[0m \033[1;36mFam\033[0m\033[1;35m-\033[0m\033[1;36mHacker\033[0m\033[1;35m_\033[0m\033[1;36mClient\033[0m"
echo " "
echo " "
cd "/data/data/com.termux/files/home/storage/shared/Fam-Hacker_Client/"
echo " "
sleep 2.0
echo " "
echo -e "\e[35m[\e[0m\e[36mPress\e[0m\e[35m]\e[0m \e[34mPress\e[0m \e[36many\e[0m \e[34mbutton to continue\e[0m"
read
clear

## Move Completed File
echo " "
echo " "
echo " "
echo -e "\e[36mFam\e[0m\e[35m-\e[0m\e[36mHacker\e[0m \e[34mis ready to\e[0m \e[36mmove\e[0m \e[34mthe\e[0m \e[92mcompleted\e[0m \e[34mfile to the\e[0m \e[36mFam\e[0m\e[35m-\e[0m\e[36mHacker\e[0m\e[35m_\e[0m\e[36mClient\e[0m \e[34mdirectory\e[0m"
echo " "
echo -e "\e[34mPlease\e[0m \e[34mpress\e[0m \e[36many\e[0m \e[34mbutton to\e[0m \e[36mexecute\e[0m \e[34mthe process\e[0m"
echo " "
read
echo " "
shopt -s extglob
mv "$(ls -td -- */ | head -n1)" /data/data/com.termux/files/home/storage/shared/Fam-Hacker_Flud-Pit
sleep 1.0

## Removing Files in /data/data/com.termux/files/home/downloads/
rm -rf /data/data/com.termux/files/home/downloads/*
echo " "
echo " "
echo -e "\e[33mExecution Success\e[0m\e[31m!\e[0m"
sleep 1.0

## Quit Menu
echo " "
echo -e "\e[95m[\e[0m\e[34mEnter\e[0m\e[95m]\e[0m \e[34mPress The\e[0m \e[36mEnter\e[0m \e[34mKey Or\e[0m \e[36mAny\e[0m \e[34mKey To\e[0m \e[93mQuit\e[0m"
echo " "
echo " "
read