#!/data/data/com.termux/files/usr/bin/bash
# Project name : Fam-Hacker_Client
# Coded by: tthatgguy1 (You dont become a coder by just changing the credits)
# Github: https://github.com/tthatgguy1/Fam-Hacker_Client
# Date : 12/04/2024

## Sound 1
clear
mpv ~/storage/shared/Fam-Hacker_Client/sfx/Secret_Sound.mp3 >/dev/null 2>/dev/null
echo " "
echo " "
sleep 1.0

## Torrent Logo & Date
echo " "
echo " "
clear
echo '
███████╗ █████╗  ███╗───███╗  ██╗──██╗ ─█████╗  ─██████╗ ██╗──██╗ ██████╗
██╔════╝██╔══██╗ ████╗─████║  ██║──██║ ██╔══██╗ ██╔════╝ ██║─██╔╝ ██╔══██╗
█████╗──███████║ ██╔████╔██║  ███████║ ███████║ ██║──────█████╔╝──██████╔╝
██╔══╝──██╔══██║ ██║╚██╔╝██║  ██╔══██║ ██╔══██║ ██║──────██╔═██╗──██╔══██╗
██║─────██║──██║ ██║─╚═╝─██║  ██║──██║ ██║──██║ ─██████╗ ██║──██╗ ██║──██║
╚═╝─────╚═╝──╚═╝ ╚═╝─────╚═╝  ╚═╝──╚═╝ ╚═╝──╚═╝  ╚═════╝ ╚═╝──╚═╝ ╚═╝──╚═╝
───████████╗ ██████╗ ██████╗ ██████╗ ███████╗███╗───██╗████████╗
───╚══██╔══╝██╔═══██╗██╔══██╗██╔══██╗██╔════╝████╗──██║╚══██╔══╝
──────██║───██║───██║██████╔╝██████╔╝█████╗──██╔██╗ ██║───██║   
──────██║───██║───██║██╔══██╗██╔══██╗██╔══╝──██║╚██╗██║───██║   
──────██║───╚██████╔╝██║──██║██║  ██║███████╗██║ ╚████║───██║   
──────╚═╝────╚═════╝ ╚═╝──╚═╝╚═╝  ╚═╝╚══════╝╚═╝  ╚═══╝   ╚═╝   
---------------------------[Nah-Fam_Studios]------------------------------' | lolcat
echo " "
echo " "
				  'date' | lolcat \-a
echo " "

## File Info
cd downloads
newf=$(ls -Art | tail -n 1)
echo " "
cowsay -f meow "${newf}" | lolcat
toilet -f small 'Downloading' -F border | lolcat \-a
echo " "
echo " "
sleep 1.0

## Aria2 Download
echo -e  "To \033[1;31mQuit\033[0m press \033[1;31mctrl\033[0m \033[1;33m+\033[0m \033[1;31mC\033[0m \033[1;33mtogether\033[0m, and then press \033[1;32mEnter\033[0m"
echo -e "\e[32m"
echo " "
"aria2c" --seed-time=0 --summary-interval=5000 --max-connection-per-server=10 -d /data/data/com.termux/files/home/storage/shared/Fam-Hacker_Client "/data/data/com.termux/files/home/downloads/${newf}" 
echo " "
echo -e " \e(B\e[m"
echo " "
sleep 1.0

## Sound 2
mpv ~/storage/shared/Fam-Hacker_Client/sfx/TLOZ-WW_Heart_Container.mp3 >/dev/null 2>/dev/null
echo " "
sleep 1.0

## Removing Files in /data/data/com.termux/files/home/downloads/
rm -rf /data/data/com.termux/files/home/downloads/*
echo " "
sleep 1.0

## Quit Menu
echo " "
echo -e "[\033[1;31mEnter\033[0m] Press Enter to \033[1;33mQuit\033[0m\033[1;31m!\033[0m"
echo " "
echo -e "\033[1;33m1\033[0m.[\033[1;31mDelete\033[0m] all the data in\033[1;31m-\033[0m\033[1;33m[\033[0m\033[1;31mFam\033[1;33m-\033[0m\033[1;31mHacker\033[0m\033[1;33m_\033[0m\033[1;31mClient\033[0m\033[1;33m]\033[0m."
read bxx                                                                
case $bxx in

	1) echo "Are you sure you want to Delete all the data in Torrent-Downloads folder(Y/n)"
	
	read xconf

	if [ "$xconf" != "${xconf#[Yy]}" ] ; then
		echo "Deleting all the data in the Torrent-Downloads folder..."
		cd /data/data/com.termux/files/home/storage/shared/Fam-Hacker_Client
		rm - rf *
		cd
	else
		echo "Quiting the Menu.."

	fi
	;;

#Fam Un-Named
echo '
                        _
                      .!=!.
                      \===/
                      |>X<|
                      |>X<|
                      |>X<|
                      |>X<|
                      |>X<|
                      |>X<|
                      |>X<|
                      |>X<|
                     .-----.
                 /\__:-----:__/\
              ./ ._.  \.-./  ._. \.
            ./ ./  -.   V   .-  \. \.
           /__/        \ /        \__\
                      |>X<|
                      |>X<|
                     / . . \
                    |!.V V.!|
                     \\ V //
                      |>X<|
                      |>X<|
                      |>X<|
                      |>X<|
                      |>X<|
                      |>X<|
                      |>X<|
                      |>X<|
                      |>X<|
                      |>X<|
                      \\ //
                       \V/'

esac
